#ifndef DOCUMENTS_MAINPAGE_H_
#define DOCUMENTS_MAINPAGE_H_

// This file defines what appears on the Main Page of the documentation
// generated by doxygen. The file contains no code, and does not appear
// in any cpp include statement.
//
/*!
 * \mainpage System Agnostic Background Error Representation
 *
 * \section IntroSection Introduction
 * Welcome to the documentation for the System Agnostic Background Error 
 * Representation (SABER)
 *
 * \section DirStructure Directory structure
