version: 0.2

env:
  parameter-store:
    GIT_USER: "/CodeBuild/Git_USER"
    GIT_PASS: "/CodeBuild/Git_PASS"

phases:
  install:
    commands:
      - echo Executing install phase
    finally:
      - echo install Finally
  pre_build:
    commands:
      - echo Executing pre_build phase
      - pwd
      - ls
      - cd ../ 
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/saber-bundle saber-bundle
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/oops saber-bundle/oops 
      - git clone https://$GIT_USER:$GIT_PASS@github.com/jcsda/fckit saber-bundle/fckit
      - mv saber saber-bundle
      - mkdir build
      - ls
      - ls saber-bundle
      - cd saber-bundle
      - sed -i 's/BRANCH develop  UPDATE//' CMakeLists.txt
      - cd ..
  build:
    commands:
      - echo Executing build phase
      - cd build
      - ecbuild ../saber-bundle
      - make -j4
      - ctest 
  post_build:
    commands:
      - echo Executing post_build phase
    finally:
      - echo post_build Finally




