version: 0.2

env:
  parameter-store:
    envvar: helloWorldSecure
#    GIT_USER:
#    GIT_PASS:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo Executing install phase
      - echo {{ssm:alias/aws/ssm/helloWorldSecure}}
      - echo {ssm:alias/aws/ssm/helloWorldSecure}
#      - echo {envvar}
    finally:
      - echo install Finally
  pre_build:
    commands:
      - ecbuild 
      - echo Executing pre_build phase
      - pwd
      - ls
      - cd ../ 
      - git clone https://github.com/jcsda/saber-bundle saber-bundle
      - git clone https://github.com/jcsda/oops saber-bundle/oops 
      - git clone https://github.com/jcsda/fckit saber-bundle/fckit
      - mv saber saber-bundle

      - ls 
    finally:
      - echo pre_build Finally

  build:
    commands:
      - echo Executing build phase
    finally:
      - echo build Finally

  post_build:
    commands:
      - echo Executing post_build phase
    finally:
      - echo post_build Finally




