/*
 * (C) Crown Copyright 2023-2025 Met Office
 *
 * This software is licensed under the terms of the Apache Licence Version 2.0
 * which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * This block is to allow us to transform an increment into its filter residual by 
 * reading a file:
 *   residual = file_data - original_increment.
 *
 * It is typically used in conjunction with saber block WriteFields for
 * situations where we need to take the difference (in say ProcessPerts)
 * but don't have easy access to the file data at the point we need to create
 * the residual
 */


#include "saber/generic/ResidualFields.h"

#include <sys/stat.h>
#include <sstream>

#include "atlas/functionspace.h"
#include "atlas/grid/detail/partitioner/TransPartitioner.h"
#include "atlas/grid/Partitioner.h"
#include "atlas/mesh.h"
#include "atlas/meshgenerator/detail/StructuredMeshGenerator.h"
#include "atlas/output/Gmsh.h"

#include "eckit/exception/Exceptions.h"

#include "oops/base/FieldSet3D.h"
#include "oops/mpi/mpi.h"
#include "oops/util/FieldSetOperations.h"
#include "oops/util/Logger.h"
#include "oops/util/ParallelFieldSetIO.h"

namespace saber {
namespace generic {

// -----------------------------------------------------------------------------

static SaberOuterBlockMaker<ResidualFields> makerResidualFields_("residual fields");

// -----------------------------------------------------------------------------

ResidualFields::ResidualFields(const oops::GeometryData & outerGeometryData,
                         const oops::Variables & outerVars,
                         const eckit::Configuration & covarConfig,
                         const Parameters_ & params,
                         const oops::FieldSet3D & xb,
                         const oops::FieldSet3D & fg)
  : SaberOuterBlockBase(params, xb.validTime(), outerGeometryData, outerVars),
    innerGeometryData_(outerGeometryData),
    innerVars_(outerVars),
    params_(params),
    io_(),
    count_multiply_(1)
{
  oops::Log::trace() << classname() << "::ResidualFields starting" << std::endl;

  if (params_.readParallelIONetCDFFile) {
#ifdef ATLAS_VERSION_46_OR_GREATER
    const auto gridName = outerGeometryData.functionSpace().grid().name();
    io_.reset(new util::ParallelFieldSetIO(outerGeometryData.functionSpace(), gridName,
                                           util::ParallelFieldSetIO::Mode::Read));
#else
    auto fsType = outerGeometryData.functionSpace().type();
    if (fsType == "StructuredColumns") {
      auto fs = atlas::functionspace::StructuredColumns(outerGeometryData.functionSpace());
      io_.reset(new util::ParallelFieldSetIO(fs, fs.grid().name(),
                                             util::ParallelFieldSetIO::Mode::Read));
    } else {
      // Error Trap
      throw eckit::NotImplemented("parallel IO only supporting StructuredColumns for now",
                                  Here());
    }
#endif
  }

  oops::Log::trace() << classname() << "::ResidualFields done" << std::endl;
}

// -----------------------------------------------------------------------------

void ResidualFields::multiply(oops::FieldSet3D & fset) const {
  oops::Log::trace() << classname() << "::multiply starting" << std::endl;

  oops::FieldSet3D fileFset(fset.validTime(), fset.commGeom());
  fileFset.deepCopy(fset);
  fileFset.zero();
  std::stringstream filepath;
  // Note that the count_multiply_ here is needed to mirror the file names
  // generated by WriteFields saber block. That way we can ensure that we have
  // consistency between writing and reading.
  filepath << params_.inputPath.value() << "/"
           << params_.multiplyFileName.value() << "_" << count_multiply_++;
  const std::string filepathnc = filepath.str() + ".nc";
  eckit::LocalConfiguration conf;
  conf.set("filepath", filepath.str());
  conf.set("filename", filepathnc);

  oops::Variables readVars;
  for (auto fldvarname : params_.fieldNames.value()) {
    readVars.push_back(innerVars_[fldvarname]);
  }

  params_.readParallelIONetCDFFile ?
    fileFset.read(fset.fieldSet()[0].functionspace(), readVars, *io_, conf) :
    fileFset.read(fset.fieldSet()[0].functionspace(), readVars, conf);

  fset -= fileFset;
  fset *= -1.0;

  oops::Log::trace() << classname() << "::multiply done" << std::endl;
}

// -----------------------------------------------------------------------------

void ResidualFields::multiplyAD(oops::FieldSet3D & fset) const {
  oops::Log::trace() << classname() << "::multiplyAD starting" << std::endl;
  throw eckit::NotImplemented("residualFields adjoint not implemented",
                                  Here());
  oops::Log::trace() << classname() << "::multiplyAD done" << std::endl;
}


// -----------------------------------------------------------------------------

void ResidualFields::print(std::ostream & os) const {
  os << classname();
}

// -----------------------------------------------------------------------------

}  // namespace generic
}  // namespace saber
